// Run: node tests/statistics_archive.mjs [path/to/pglite/dist/index.js]
process.on('uncaughtException', e => { console.error(e.message, e.position, e.where || ''); process.exit(1); });
import { pathToFileURL } from 'node:url';
const { PGlite } = await import(process.argv[2] ? pathToFileURL(process.argv[2]).href : '@electric-sql/pglite');
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite();
await db.exec(`
create role anon; create role authenticated; create role service_role bypassrls;
create table high_season(season integer primary key, pris_morgenmad numeric, pace_archived boolean default false);
create table hk_dtb (
 id bigint generated by default as identity primary key, season integer, booking_number integer,
 navn text, familie_navn text, checkin_date date, checkout_date date, booking_date timestamptz,
 nation text, web text, known text, morgenmad text, rabat text, pris text, numb_guests integer,
 email text, telefon text, spouse text, comments text
);
`);
for (const name of ['20260820_create_historie.sql','20260905_add_booking_pace_fields_to_historie_new.sql','20260909_booking_pace_season_status.sql','20260910_close_booking_season.sql','20260910_create_statistik_historik.sql','20260910_statistics_season_archive.sql','20260910_statistics_season_null_values.sql']) {
  await db.exec(fs.readFileSync('supabase/migrations/'+name,'utf8'));
}
const rows = async (q) => (await db.query(q)).rows;
await db.exec(`
insert into high_season values (2026,100,false),(2027,100,false),(2028,100,false),(2029,100,false),(2030,100,false);
insert into hk_dtb (season,booking_number,navn,checkin_date,checkout_date,booking_date,nation,web,known,morgenmad,rabat,pris,numb_guests)
values
(2026,1,'Test','2026-05-31','2026-06-02','2026-01-01',' dk ','web','Y','Y','10%','1000,50',2),
(2026,2,'Test','2026-06-03','2026-06-05','2026-01-01',null,'BC','N','N','0','500',1),
(2026,3,'Test','2026-06-03','2026-06-05','2026-01-01','DE','CAN-SL','N','N','0','9999',2),
(2026,3,'Test','2026-06-03','2026-06-05','2026-01-01','DE','web','N','N','0','9999',2),
(2027,1,'Test','2027-05-31','2027-06-02','2027-01-01','DK','web','Y','Y','10','1000',2),
(2028,1,'Test','2028-06-03','2028-06-05',null,'DK','web','N','N','0','500',1),
(2029,1,'Test','2029-06-03','2029-06-05','2029-01-01','DK','web','N','N','0','bad price',1);
insert into historie_new(season,booking_nr,navn,booking_date,room_nights,storage_path)
values(2026,1,'Archived name','2026-01-01',4,'keep-this-document');
`);
const reports = await rows('select * from calculate_season_statistics(2026)');
const report = name => reports.find(r=>r.report_type===name);
assert.equal(reports.length,8);
assert.equal(report('room_nights').data[0].room_nights,4);
assert.deepEqual(report('danmarks_statistik').data,[{country_group:'DK',arrivals:2,guest_nights:4}]);
assert.equal(report('gross_revenue_monthly').data.find(r=>r.month===6).gross_revenue,1500.50);
assert.equal(report('gross_revenue_monthly').data.length,12);
assert.equal(report('breakfast_monthly').data.find(r=>r.month===5).net_revenue,144);
assert.equal(report('breakfast_monthly').data.find(r=>r.month===6).net_revenue,144);
assert.equal(report('room_nights').metadata.missing_country_rows,1);
if (process.env.STATISTICS_TEST_REPORTS) fs.writeFileSync(process.env.STATISTICS_TEST_REPORTS, JSON.stringify(reports));
const original = await rows('select * from historie_new where season=2026');
await db.query('select close_booking_season(2026)');
assert.deepEqual(await rows('select * from historie_new where season=2026'),original);
const frozen = await rows('select * from statistik_historik where season=2026 order by report_type');
assert.equal(frozen.length,8);
await db.exec("update hk_dtb set pris='999999' where season=2026");
await db.query('select close_booking_season(2026)');
assert.deepEqual(await rows('select * from statistik_historik where season=2026 order by report_type'),frozen);
await db.query('select close_booking_season(2027)');
assert.equal((await rows('select count(*)::int as n from historie_new where season=2027'))[0].n,1);
assert.equal((await rows('select count(*)::int as n from statistik_historik where season=2027'))[0].n,8);
assert.equal((await rows('select count(*)::int as n from hk_dtb where season=2027'))[0].n,1);
for (const year of [2028,2029]) {
  await assert.rejects(db.query(`select close_booking_season(${year})`));
  assert.equal((await rows(`select count(*)::int as n from statistik_historik where season=${year}`))[0].n,0);
  assert.equal((await rows(`select pace_archived from high_season where season=${year}`))[0].pace_archived,false);
}
const empty = await rows('select * from calculate_season_statistics(2030)');
assert.equal(empty.length,8);
assert.equal(empty.find(r=>r.report_type==='room_nights').data[0].room_nights,0);
assert.equal((await rows("select jsonb_array_length(data) as n from statistik_historik where season=2024"))[0].n,5);
// Running the migration twice must not modify frozen reports or legacy data.
await db.exec(fs.readFileSync('supabase/migrations/20260910_statistics_season_archive.sql','utf8'));
assert.deepEqual(await rows('select * from statistik_historik where season=2026 order by report_type'),frozen);
// Reapply latest migration after explicitly testing the previous migration's retry.
await db.exec(fs.readFileSync('supabase/migrations/20260910_statistics_season_null_values.sql','utf8'));
await db.exec(`
insert into high_season values (2031,100,false);
insert into hk_dtb (season,booking_number,navn,checkin_date,checkout_date,booking_date,nation,web,morgenmad,pris,numb_guests)
values
(2031,1,'Test','2031-06-01','2031-06-03','2031-01-01','DK','web','N','1200',4),
(2031,1,'Test','2031-06-01','2031-06-03',null,'DK','web','N',null,null),
(2031,2,'Test','2031-06-01','2031-06-03','2031-01-01','DK','web','N',null,1);
`);
const companion = await rows('select * from calculate_season_statistics(2031)');
assert.equal(companion[0].metadata.invalid_rows,0);
assert.equal(companion.find(r=>r.report_type==='room_nights').data[0].room_nights,6);
assert.equal(companion.find(r=>r.report_type==='gross_revenue_monthly').data.find(r=>r.month===6).gross_revenue,1200);
assert.equal(companion.find(r=>r.report_type==='danmarks_statistik').data[0].arrivals,5);
assert.equal(companion.find(r=>r.report_type==='danmarks_statistik').data[0].guest_nights,10);
for (const change of ["pris='bad'", "numb_guests=-1", "numb_guests=null"]) {
    await db.exec(`begin; update hk_dtb set ${change} where season=2031 and booking_number=2;`);
    const invalid = await rows('select * from calculate_season_statistics(2031)');
    assert.equal(invalid[0].metadata.invalid_rows,1);
    await assert.rejects(db.query('select close_booking_season(2031)'));
    await db.exec('rollback');
}
await db.query('select close_booking_season(2031)');
assert.equal((await rows('select count(*)::int as n from statistik_historik where season=2031'))[0].n,8);
console.log('NULL companion checks passed: no double counting, NULL price accepted, malformed amounts/negative guests/missing main guests still rejected, season closes.');
await db.exec('set role anon');
await assert.rejects(db.query('select * from calculate_season_statistics(2026)'));
await db.exec('reset role');
console.log('SQL integration checks passed: all reports, cancellation, month split, 2026 preservation, 2027 copy, immutable retry, rollback, empty season, migration retry, permissions.');
await db.close();
