create table if not exists public.historie_new (
    id bigint generated by default as identity primary key,
    season integer not null,
    booking_nr integer not null,
    navn text not null,
    familie_navn text,
    indcheck date,
    udcheck date,
    created_at timestamptz not null default now(),
    nationalitet text,
    web text,
    email text,
    phone text,
    spouce text,
    comments text,
    storage_path text,
    delete_at timestamptz,

    constraint historie_new_season_booking_nr_unique unique (season, booking_nr),
    constraint historie_new_ophold_dates_check
        check (udcheck is null or indcheck is null or udcheck >= indcheck)
);

-- CREATE TABLE IF NOT EXISTS does not add columns when historie_new already exists.
-- These statements safely extend the existing table without removing data.
alter table public.historie_new add column if not exists season integer;
alter table public.historie_new add column if not exists booking_nr integer;
alter table public.historie_new add column if not exists navn text;
alter table public.historie_new add column if not exists familie_navn text;
alter table public.historie_new add column if not exists indcheck date;
alter table public.historie_new add column if not exists udcheck date;
alter table public.historie_new
    add column if not exists created_at timestamptz not null default now();
alter table public.historie_new add column if not exists nationalitet text;
alter table public.historie_new add column if not exists web text;
alter table public.historie_new add column if not exists email text;
alter table public.historie_new add column if not exists phone text;
alter table public.historie_new add column if not exists spouce text;
alter table public.historie_new add column if not exists comments text;
alter table public.historie_new add column if not exists storage_path text;
alter table public.historie_new add column if not exists delete_at timestamptz;

comment on table public.historie_new is
    'Historik over gaestebookinger og reference til gaesteregistrering i privat Storage.';

comment on column public.historie_new.storage_path is
    'Filsti i Supabase Storage; eksempelvis guest-registrations/2026/2026-104.pdf.';

create index if not exists historie_new_navn_idx
    on public.historie_new (navn, familie_navn);

create index if not exists historie_new_email_idx
    on public.historie_new (email);

create index if not exists historie_new_delete_at_idx
    on public.historie_new (delete_at)
    where delete_at is not null;

alter table public.historie_new enable row level security;
